### ISSUE TITLE
Bulk rendering 'Thaumcraft' only renders the chest

### ISSUE THREAD

**Issue by xbony2** [unascribed/BlockRenderer#2]
Doing the magic combination, typing the ID, and clicking render only dumps one item, and not even from the mod- the Chest.

(Tested on FTB Unstable, probably not the best environment)

**Comment by exaskye** [comment]
What's the ID you're rendering? It has to be the same as the one you use for /give, and is case-sensitive. No idea why it would only dump the chest, though.

**Comment by xbony2** [comment]
I tried "Thaumcraft", which is valid through /give.

**Comment by exaskye** [comment]
Damn it, how many times am I going to mix up these two issues!?

**Comment by exaskye** [comment]
Got distracted playing with wand foci...

Thaumcraft's mod id is actually 'thaumcraft', not 'Thaumcraft'. (Same as in /give, though the command seems to be case-insensitive) Renders seem to work fine.

The chest got rendered due to some stale debug code I forgot to remove, back from when I was troubleshooting problems rendering special blocks like the chest.
