### ISSUE TITLE
Port to new versions?

### ISSUE THREAD

**Issue by BetaCarotina** [unascribed/BlockRenderer#24]
This mod seems dead, but I really hope that someone will port it to 1.13/1.14/1.15

**Comment by exaskye** [comment]
I've stopped modding, but there appears to be a fork that has an incomplete port to 1.15 and 1.14: https://github.com/xbony2/BlockRenderer

**Comment by AterAnimAvis** [comment]
Here, have a port or two.

I decided to skip the 1.13 port, I may come back and do a port if there is interest.
Note that the rendering portion is mostly a straight port and will probably at some point be moved to the new Rendering System.


Unascribed, do I have your permission to put this up on CurseForge?

<hr>

Versions:
- [Minecraft 1.16-20w18a (Fabric)](https://github.com/AterAnimAvis/BlockRenderer/releases/tag/20w18a-1.1.0)
- [Minecraft 1.15.2 (Forge)](https://github.com/AterAnimAvis/BlockRenderer/releases/tag/1.15-1.1.0)
- [Minecraft 1.14.4 (Forge)](https://github.com/AterAnimAvis/BlockRenderer/releases/tag/1.14-1.1.0) 
- [Github Repo](https://github.com/AterAnimAvis/BlockRenderer)

<hr>

Additional Features:
- Render size is now no longer limited by the window size but by a fixed limit of 2048. (Using Brian Paul's TR Library)
- Pressing the keybinding whilst holding an item in the main-hand will render it
- Customize Render Size (Press **[Alt]** to configure single Item Renders)
- Use Identifier for Filename (Press **[Alt]** to configure single Item Renders)
- Add Render Size to Filename (Press **[Alt]** to configure single Item Renders)

<hr>

Known Bugs / Issues:
- Pressing the keybind whilst in a container can be iffy due to widgets grabbing focus and not passing on the event, I've fixed this by checking the raw keycode however for compatibility.
    - If you have a recipe book open the keybind is disabled.
    - If a textfield is focused the keybind is disabled.
- The current OpenGl calls are pretty much a direct copy, this could probably be cleaned up due to changes in the rendering system.

**Comment by exaskye** [comment]
I don't like the filename changes; the filenames are the way they are due to multiple specific requests by FTB Wiki maintainers. It sounds like they might be customizable but only for single renders...?

Alt keybinds are likely to be unusable in many cases on Linux. Tiled rendering is a good upgrade.

Why should I have to give you permission to put it on Curse? It's MIT, like I could give a shit.

**Comment by AterAnimAvis** [comment]
Pressing the Alt key whilst doing a single render opens a UI which is like the Bulk Render UI but without the Enter Mod Id (Renamed to Namespace to fit with newer versions).

The filename changes are optional for both Bulk/Single renders.
The changes are applied by checkboxes that default to false in each UI.

There was only one real change to filenames which was that the render size was added by default for single renders.
This is actually a remnant of testing so there's an update with this changed back.

Thanks for the information on alt keys on Unix systems.
My current work around is a button in the UI to set the render size based on the GUI Scale, with Shift now opening the UI instead.

I know the License is MIT but thought it be polite to ask seeing as I was posting the above message anyway.

A CurseForge Project has been made [here](https://www.curseforge.com/minecraft/mc-mods/block-renderer) (N.B. Not visible until moderation by Curse).
